output-format: pylint
strictness: veryhigh
test-warnings: true
doc-warnings: true

ignore-paths:
  - .env

pylint:
  run: true
  disable:
    - too-few-public-methods
    - line-too-long # Already checked by pep8
    - too-many-arguments
    - unsubscriptable-object # https://github.com/PyCQA/pylint/issues/3882

mccabe:
  run: true

pep257:
  run: true
  disable:
    - D102
    - D203
    - D213
    - D407

pep8:
  options:
    max-line-length: 120
  disable:
    - E261

pyflakes:
  run: true
  disable:
    - F401

pyroma:
  run: true

mypy:
  run: true
  options:
    ignore-missing-imports: true
    strict: true
