name: Checks

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    strategy:
      max-parallel: 8
      matrix:
        linter: ['flake8', 'isort', 'black', 'pylint', 'mypy']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Setup Nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Lint
      run: nox -s ${{ matrix.linter }}

  checks:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Run Unit Tests
      run: nox -s tests-${{ matrix.python-version }}

    - name: Upload Coverage
      if: matrix.python-version == '3.9'
      run: |
        pip install coveralls
        coveralls 
      env:
        COVERALLS_SERVICE_NAME: github
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
