name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    name: Publish to Pypi
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Publish
      run: nox -s publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
